server:
  port: 9600
spring:
  application:
    name: prb-retry
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.81:3306/user_center?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.31.81
    port: 6379
  cache:
    redis:
      time-to-live: 60000
logging:
  level:
    com:
      prb:
        mapper: debug
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
