server:
  port: 9500
spring:
  application:
    name: prb-mybatis-plus
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.81:3306/user_center?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

logging:
  level:
    com:
      prb:
        mapper: debug
